---
- name: join worker nodes to cluster
  shell: "{{ hostvars[groups['Kuberentes_Master'] | first]['join_command'] }} --cri-socket=unix:///var/run/cri-dockerd.sock"
  args:
    creates: /etc/kubernetes/kubelet.conf
